-- Gnadental LS25 Roleplay
-- Dieses Skript im Supabase SQL Editor komplett ausfuehren.
-- Hinweis: Die anon-Policies sind fuer den aktuellen Entwicklungsmodus des
-- Frontends gedacht. Vor dem Livegang durch Supabase Auth und Rollen ersetzen.

create extension if not exists pgcrypto;

create table if not exists public.citizens (
  citizen_id text primary key,
  first_name text not null check (length(trim(first_name)) between 1 and 60),
  last_name text not null check (length(trim(last_name)) between 1 and 60),
  birthdate date not null,
  created_at timestamptz not null default now()
);

create table if not exists public.companies (
  id bigint generated by default as identity primary key,
  company_name text not null check (length(trim(company_name)) between 1 and 100),
  owner_citizen_id text references public.citizens(citizen_id) on update cascade on delete set null,
  sector text not null default 'Landwirtschaft',
  description text not null default '',
  status text not null default 'pending' check (status in ('pending', 'active', 'rejected')),
  created_at timestamptz not null default now()
);

create table if not exists public.accounts (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('privat', 'unternehmen')),
  citizen_id text references public.citizens(citizen_id) on update cascade on delete cascade,
  company_id bigint references public.companies(id) on update cascade on delete cascade,
  balance numeric(12, 2) not null default 0 check (balance >= 0),
  status text not null default 'pending' check (status in ('pending', 'active', 'blocked')),
  created_at timestamptz not null default now(),
  check ((type = 'privat' and citizen_id is not null and company_id is null)
      or (type = 'unternehmen' and company_id is not null and citizen_id is null))
);

create unique index if not exists accounts_one_active_citizen
  on public.accounts(citizen_id) where status = 'active';
create unique index if not exists accounts_one_active_company
  on public.accounts(company_id) where status = 'active';

create table if not exists public.invoices (
  id bigint generated by default as identity primary key,
  invoice_number text not null unique,
  from_account_id bigint not null references public.accounts(id) on delete restrict,
  to_account_id bigint not null references public.accounts(id) on delete restrict,
  amount numeric(12, 2) not null check (amount > 0),
  reason text not null default 'Rechnung',
  status text not null default 'open' check (status in ('open', 'paid', 'cancelled')),
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  check (from_account_id <> to_account_id)
);

create table if not exists public.vehicles (
  vehicle_id text primary key,
  name text not null,
  vehicle_class text not null,
  price numeric(12, 2) not null default 0 check (price >= 0),
  availability text not null default 'verkauf' check (availability in ('verkauf', 'miete')),
  status text not null default 'neu' check (status in ('neu', 'active', 'Occasion')),
  owner_citizen_id text references public.citizens(citizen_id) on update cascade on delete set null,
  company_id bigint references public.companies(id) on update cascade on delete set null,
  created_at timestamptz not null default now(),
  check (not (owner_citizen_id is not null and company_id is not null))
);

create table if not exists public.licenses (
  id bigint generated by default as identity primary key,
  citizen_id text not null references public.citizens(citizen_id) on update cascade on delete cascade,
  license_class text not null check (length(trim(license_class)) between 1 and 20),
  created_at timestamptz not null default now(),
  unique (citizen_id, license_class)
);

create table if not exists public.logistics (
  id bigint generated by default as identity primary key,
  item_name text not null,
  quantity integer not null check (quantity > 0),
  unit_price numeric(12, 2) not null check (unit_price >= 0),
  direction text not null check (direction in ('eingang', 'ausgang')),
  created_at timestamptz not null default now()
);

create table if not exists public.logistics_items (
  id bigint generated by default as identity primary key,
  item_name text not null unique,
  unit_price numeric(12, 2) not null default 0 check (unit_price >= 0),
  quantity integer not null default 0 check (quantity >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  account_id bigint not null references public.accounts(id) on delete restrict,
  items_json jsonb not null default '[]'::jsonb check (jsonb_typeof(items_json) = 'array'),
  total_amount numeric(12, 2) not null check (total_amount > 0),
  status text not null default 'paid' check (status in ('created', 'paid', 'cancelled')),
  created_at timestamptz not null default now()
);

create index if not exists companies_owner_idx on public.companies(owner_citizen_id);
create index if not exists accounts_citizen_idx on public.accounts(citizen_id);
create index if not exists accounts_company_idx on public.accounts(company_id);
create index if not exists invoices_status_idx on public.invoices(status);
create index if not exists vehicles_citizen_idx on public.vehicles(owner_citizen_id);
create index if not exists vehicles_company_idx on public.vehicles(company_id);

create or replace function public.touch_logistics_item()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists logistics_items_touch on public.logistics_items;
create trigger logistics_items_touch
before update on public.logistics_items
for each row execute function public.touch_logistics_item();

create or replace function public.pay_invoice(invoice_id bigint)
returns public.invoices
language plpgsql
security definer
set search_path = public
as $$
declare
  invoice_row public.invoices;
  sender public.accounts;
  receiver public.accounts;
begin
  select * into invoice_row from public.invoices where id = invoice_id for update;
  if not found then raise exception 'Rechnung nicht gefunden'; end if;
  if invoice_row.status <> 'open' then raise exception 'Rechnung ist bereits bearbeitet'; end if;

  select * into sender from public.accounts where id = invoice_row.from_account_id for update;
  select * into receiver from public.accounts where id = invoice_row.to_account_id for update;
  if sender.status <> 'active' or receiver.status <> 'active' then
    raise exception 'Beide Konten muessen aktiv sein';
  end if;
  if sender.balance < invoice_row.amount then raise exception 'Guthaben reicht nicht aus'; end if;

  update public.accounts set balance = balance - invoice_row.amount where id = sender.id;
  update public.accounts set balance = balance + invoice_row.amount where id = receiver.id;
  update public.invoices set status = 'paid', paid_at = now() where id = invoice_row.id returning * into invoice_row;
  return invoice_row;
end;
$$;

create or replace function public.create_order(account_id bigint, items_json jsonb, total_amount numeric)
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  account_row public.accounts;
  order_row public.orders;
begin
  if total_amount is null or total_amount <= 0 then raise exception 'Bestellwert muss groesser als 0 sein'; end if;
  if items_json is null or jsonb_typeof(items_json) <> 'array' or jsonb_array_length(items_json) = 0 then
    raise exception 'Warenkorb ist leer';
  end if;
  select * into account_row from public.accounts where id = account_id for update;
  if not found or account_row.status <> 'active' then raise exception 'Konto ist nicht aktiv'; end if;
  if account_row.balance < total_amount then raise exception 'Guthaben reicht nicht aus'; end if;

  update public.accounts set balance = balance - total_amount where id = account_row.id;
  insert into public.orders(account_id, items_json, total_amount, status)
    values (account_row.id, items_json, total_amount, 'paid') returning * into order_row;
  return order_row;
end;
$$;

grant execute on function public.pay_invoice(bigint) to anon, authenticated;
grant execute on function public.create_order(bigint, jsonb, numeric) to anon, authenticated;

-- Entwicklungsmodus: Das HTML nutzt den anon-Key ohne Login.
alter table public.citizens enable row level security;
alter table public.companies enable row level security;
alter table public.accounts enable row level security;
alter table public.invoices enable row level security;
alter table public.vehicles enable row level security;
alter table public.licenses enable row level security;
alter table public.logistics enable row level security;
alter table public.logistics_items enable row level security;
alter table public.orders enable row level security;

do $$
declare
  table_name text;
begin
  foreach table_name in array array['citizens','companies','accounts','invoices','vehicles','licenses','logistics','logistics_items','orders'] loop
    execute format('drop policy if exists %I on public.%I', 'dev_public_access_' || table_name, table_name);
    execute format('create policy %I on public.%I for all to anon, authenticated using (true) with check (true)', 'dev_public_access_' || table_name, table_name);
  end loop;
end;
$$;

do $$
begin
  alter publication supabase_realtime add table public.citizens;
  alter publication supabase_realtime add table public.companies;
  alter publication supabase_realtime add table public.accounts;
  alter publication supabase_realtime add table public.invoices;
  alter publication supabase_realtime add table public.vehicles;
  alter publication supabase_realtime add table public.licenses;
  alter publication supabase_realtime add table public.logistics_items;
  alter publication supabase_realtime add table public.orders;
exception when duplicate_object then null;
end;
$$;

-- Optionale Startdaten. IDs werden nur einmal angelegt.
insert into public.citizens(citizen_id, first_name, last_name, birthdate)
values ('CIT-0001', 'Max', 'Muster', '1990-05-12')
on conflict (citizen_id) do nothing;

insert into public.companies(company_name, owner_citizen_id, sector, description, status)
select 'Gnadental Agrar', 'CIT-0001', 'Landwirtschaft', 'Beispielbetrieb fuer den Start', 'active'
where not exists (select 1 from public.companies where company_name = 'Gnadental Agrar');

insert into public.accounts(type, citizen_id, balance, status)
select 'privat', 'CIT-0001', 10000, 'active'
where not exists (select 1 from public.accounts where citizen_id = 'CIT-0001');

insert into public.logistics_items(item_name, unit_price, quantity)
values ('Weizen', 250, 100), ('Mais', 220, 100), ('Duenger', 180, 50)
on conflict (item_name) do nothing;