-- Gnadental LS25 Roleplay
-- Dieses Skript im Supabase SQL Editor komplett ausfuehren.
-- Hinweis: Die anon-Policies sind fuer den aktuellen Entwicklungsmodus des
-- Frontends gedacht. Vor dem Livegang durch Supabase Auth und Rollen ersetzen.

create extension if not exists pgcrypto;

create table if not exists public.citizens (
  citizen_id text primary key,
  first_name text not null check (length(trim(first_name)) between 1 and 60),
  last_name text not null check (length(trim(last_name)) between 1 and 60),
  birthdate date not null,
  created_at timestamptz not null default now()
);

create table if not exists public.companies (
  id bigint generated by default as identity primary key,
  company_name text not null check (length(trim(company_name)) between 1 and 100),
  owner_citizen_id text references public.citizens(citizen_id) on update cascade on delete set null,
  sector text not null default 'Landwirtschaft',
  description text not null default '',
  status text not null default 'pending' check (status in ('pending', 'active', 'rejected')),
  created_at timestamptz not null default now()
);

create table if not exists public.accounts (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('privat', 'unternehmen')),
  citizen_id text references public.citizens(citizen_id) on update cascade on delete cascade,
  company_id bigint references public.companies(id) on update cascade on delete cascade,
  balance numeric(12, 2) not null default 0 check (balance >= 0),
  status text not null default 'pending' check (status in ('pending', 'active', 'blocked')),
  created_at timestamptz not null default now(),
  check ((type = 'privat' and citizen_id is not null and company_id is null)
      or (type = 'unternehmen' and company_id is not null and citizen_id is null))
);

create unique index if not exists accounts_one_active_citizen
  on public.accounts(citizen_id) where status = 'active';
create unique index if not exists accounts_one_active_company
  on public.accounts(company_id) where status = 'active';

create table if not exists public.invoices (
  id bigint generated by default as identity primary key,
  invoice_number text not null unique,
  from_account_id bigint not null references public.accounts(id) on delete restrict,
  to_account_id bigint not null references public.accounts(id) on delete restrict,
  amount numeric(12, 2) not null check (amount > 0),
  reason text not null default 'Rechnung',
  status text not null default 'open' check (status in ('open', 'paid', 'cancelled')),
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  check (from_account_id <> to_account_id)
);

create table if not exists public.vehicles (
  vehicle_id text primary key,
  name text not null,
  vehicle_class text not null,
  price numeric(12, 2) not null default 0 check (price >= 0),
  availability text not null default 'verkauf' check (availability in ('verkauf', 'miete')),
  status text not null default 'neu' check (status in ('neu', 'active', 'Occasion')),
  owner_citizen_id text references public.citizens(citizen_id) on update cascade on delete set null,
  company_id bigint references public.companies(id) on update cascade on delete set null,
  created_at timestamptz not null default now(),
  check (not (owner_citizen_id is not null and company_id is not null))
);

create table if not exists public.licenses (
  id bigint generated by default as identity primary key,
  citizen_id text not null references public.citizens(citizen_id) on update cascade on delete cascade,
  license_class text not null check (length(trim(license_class)) between 1 and 20),
  created_at timestamptz not null default now(),
  unique (citizen_id, license_class)
);

create table if not exists public.logistics (
  id bigint generated by default as identity primary key,
  item_name text not null,
  quantity integer not null check (quantity > 0),
  unit_price numeric(12, 2) not null check (unit_price >= 0),
  direction text not null check (direction in ('eingang', 'ausgang')),
  created_at timestamptz not null default now()
);

create table if not exists public.logistics_items (
  id bigint generated by default as identity primary key,
  item_name text not null unique,
  unit_price numeric(12, 2) not null default 0 check (unit_price >= 0),
  quantity integer not null default 0 check (quantity >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.company_warehouse (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on update cascade on delete cascade,
  product_name text not null check (length(trim(product_name)) between 1 and 100),
  amount integer not null default 0 check (amount >= 0),
  unit_price numeric(12, 2) not null default 0 check (unit_price >= 0),
  is_public boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (company_id, product_name)
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  account_id bigint not null references public.accounts(id) on delete restrict,
  items_json jsonb not null default '[]'::jsonb check (jsonb_typeof(items_json) = 'array'),
  total_amount numeric(12, 2) not null check (total_amount > 0),
  status text not null default 'paid' check (status in ('created', 'paid', 'cancelled')),
  delivery_method text not null default 'abholung' check (delivery_method in ('abholung', 'transport')),
  transport_fee numeric(12, 2) not null default 0 check (transport_fee >= 0),
  transport_status text not null default 'nicht_erforderlich' check (transport_status in ('nicht_erforderlich', 'offen', 'bestaetigt', 'unterwegs', 'zugestellt', 'storniert')),
  created_at timestamptz not null default now()
);

alter table public.orders add column if not exists delivery_method text not null default 'abholung';
alter table public.orders add column if not exists transport_fee numeric(12, 2) not null default 0;
alter table public.orders add column if not exists transport_status text not null default 'nicht_erforderlich';

create table if not exists public.transport_jobs (
  id bigint generated by default as identity primary key,
  order_id bigint references public.orders(id) on delete set null,
  account_id bigint references public.accounts(id) on delete set null,
  item_name text not null check (length(trim(item_name)) between 1 and 160),
  quantity integer not null check (quantity > 0),
  items_json jsonb not null default '[]'::jsonb check (jsonb_typeof(items_json) = 'array'),
  stock_deducted boolean not null default false,
  pickup_location text not null default 'Mezzorik Logistik',
  delivery_location text not null,
  status text not null default 'offen' check (status in ('offen', 'bestaetigt', 'unterwegs', 'zugestellt', 'storniert')),
  transport_fee numeric(12, 2) not null default 2000 check (transport_fee >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.transport_jobs add column if not exists account_id bigint references public.accounts(id) on delete set null;
alter table public.transport_jobs add column if not exists items_json jsonb not null default '[]'::jsonb;
alter table public.transport_jobs add column if not exists stock_deducted boolean not null default false;
alter table public.transport_jobs drop constraint if exists transport_jobs_status_check;
update public.transport_jobs set status = 'angenommen' where status = 'bestaetigt';
update public.transport_jobs set status = 'erledigt' where status = 'zugestellt';
alter table public.transport_jobs add constraint transport_jobs_status_check check (status in ('offen', 'angenommen', 'beladen', 'unterwegs', 'erledigt', 'storniert'));

create index if not exists companies_owner_idx on public.companies(owner_citizen_id);
create index if not exists accounts_citizen_idx on public.accounts(citizen_id);
create index if not exists accounts_company_idx on public.accounts(company_id);
create index if not exists invoices_status_idx on public.invoices(status);
create index if not exists vehicles_citizen_idx on public.vehicles(owner_citizen_id);
create index if not exists vehicles_company_idx on public.vehicles(company_id);

create or replace function public.touch_logistics_item()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists logistics_items_touch on public.logistics_items;
create trigger logistics_items_touch
before update on public.logistics_items
for each row execute function public.touch_logistics_item();

create or replace function public.touch_company_warehouse()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists company_warehouse_touch on public.company_warehouse;
create trigger company_warehouse_touch
before update on public.company_warehouse
for each row execute function public.touch_company_warehouse();

create or replace function public.touch_transport_job()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists transport_jobs_touch on public.transport_jobs;
create trigger transport_jobs_touch
before update on public.transport_jobs
for each row execute function public.touch_transport_job();

create or replace function public.pay_invoice(invoice_id bigint)
returns public.invoices
language plpgsql
security definer
set search_path = public
as $$
declare
  invoice_row public.invoices;
  sender public.accounts;
  receiver public.accounts;
begin
  select * into invoice_row from public.invoices where id = invoice_id for update;
  if not found then raise exception 'Rechnung nicht gefunden'; end if;
  if invoice_row.status <> 'open' then raise exception 'Rechnung ist bereits bearbeitet'; end if;

  select * into sender from public.accounts where id = invoice_row.from_account_id for update;
  select * into receiver from public.accounts where id = invoice_row.to_account_id for update;
  if sender.status <> 'active' or receiver.status <> 'active' then
    raise exception 'Beide Konten muessen aktiv sein';
  end if;
  if sender.balance < invoice_row.amount then raise exception 'Guthaben reicht nicht aus'; end if;

  update public.accounts set balance = balance - invoice_row.amount where id = sender.id;
  update public.accounts set balance = balance + invoice_row.amount where id = receiver.id;
  update public.invoices set status = 'paid', paid_at = now() where id = invoice_row.id returning * into invoice_row;
  return invoice_row;
end;
$$;

create or replace function public.create_order(account_id bigint, items_json jsonb, total_amount numeric)
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  account_row public.accounts;
  order_row public.orders;
begin
  if total_amount is null or total_amount <= 0 then raise exception 'Bestellwert muss groesser als 0 sein'; end if;
  if items_json is null or jsonb_typeof(items_json) <> 'array' or jsonb_array_length(items_json) = 0 then
    raise exception 'Warenkorb ist leer';
  end if;
  select * into account_row from public.accounts where id = account_id for update;
  if not found or account_row.status <> 'active' then raise exception 'Konto ist nicht aktiv'; end if;
  if account_row.balance < total_amount then raise exception 'Guthaben reicht nicht aus'; end if;

  update public.accounts set balance = balance - total_amount where id = account_row.id;
  insert into public.orders(account_id, items_json, total_amount, status)
    values (account_row.id, items_json, total_amount, 'paid') returning * into order_row;
  return order_row;
end;
$$;

create or replace function public.create_order_with_delivery(
  account_id bigint,
  items_json jsonb,
  subtotal numeric,
  delivery_method text,
  delivery_location text default null
)
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  account_row public.accounts;
  order_row public.orders;
  seller_account public.accounts;
  final_amount numeric := subtotal;
  fee numeric := 0;
begin
  if subtotal is null or subtotal <= 0 then raise exception 'Bestellwert muss groesser als 0 sein'; end if;
  if items_json is null or jsonb_typeof(items_json) <> 'array' or jsonb_array_length(items_json) = 0 then
    raise exception 'Warenkorb ist leer';
  end if;
  if delivery_method not in ('abholung', 'transport') then raise exception 'Ungueltige Lieferart'; end if;
  if delivery_method = 'transport' then
    if delivery_location is null or length(trim(delivery_location)) = 0 then raise exception 'Lieferort fehlt'; end if;
    fee := 2000;
    final_amount := subtotal + fee;
  end if;

  select * into account_row from public.accounts where id = account_id for update;
  if not found or account_row.status <> 'active' then raise exception 'Konto ist nicht aktiv'; end if;
  if account_row.balance < final_amount then raise exception 'Guthaben reicht nicht aus'; end if;

  update public.accounts set balance = balance - final_amount where id = account_row.id;
  select accounts.* into seller_account
    from public.accounts
    join public.companies on companies.id = accounts.company_id
    where lower(companies.company_name) = 'mezzorik logistik' and accounts.type = 'unternehmen' and accounts.status = 'active'
    limit 1
    for update;
  if not found then raise exception 'Mezzorik-Konto ist nicht aktiv'; end if;
  update public.accounts set balance = balance + final_amount where id = seller_account.id;
  insert into public.orders(account_id, items_json, total_amount, status, delivery_method, transport_fee, transport_status)
    values (account_row.id, items_json, final_amount, 'paid', delivery_method, fee, case when delivery_method = 'transport' then 'offen' else 'nicht_erforderlich' end)
    returning * into order_row;

  if delivery_method = 'transport' then
    insert into public.transport_jobs(order_id, account_id, item_name, quantity, items_json, delivery_location, status, transport_fee)
      values (order_row.id, account_row.id, 'Katalogbestellung', jsonb_array_length(items_json), items_json, trim(delivery_location), 'offen', fee);
  end if;
  return order_row;
end;
$$;

create or replace function public.update_transport_status(transport_job_id bigint, next_status text)
returns public.transport_jobs
language plpgsql
security definer
set search_path = public
as $$
declare
  job public.transport_jobs;
  item jsonb;
  requested_quantity integer;
  current_quantity integer;
begin
  if next_status not in ('offen', 'angenommen', 'beladen', 'unterwegs', 'erledigt', 'storniert') then
    raise exception 'Ungueltiger Transportstatus';
  end if;

  select * into job from public.transport_jobs where id = transport_job_id for update;
  if not found then raise exception 'Transportauftrag nicht gefunden'; end if;

  if next_status = 'angenommen' and not job.stock_deducted then
    for item in select * from jsonb_array_elements(job.items_json)
    loop
      requested_quantity := greatest(1, coalesce((item->>'order_quantity')::integer, 1));
      if item->>'source' = 'company' then
        select amount into current_quantity from public.company_warehouse where id = (item->>'id')::bigint for update;
        if current_quantity is null or current_quantity < requested_quantity then raise exception 'Nicht genuegend Firmenbestand fuer %', item->>'item_name'; end if;
        update public.company_warehouse set amount = amount - requested_quantity where id = (item->>'id')::bigint;
      else
        select quantity into current_quantity from public.logistics_items where id = (item->>'id')::bigint for update;
        if current_quantity is null or current_quantity < requested_quantity then raise exception 'Nicht genuegend Lagerbestand fuer %', item->>'item_name'; end if;
        update public.logistics_items set quantity = quantity - requested_quantity where id = (item->>'id')::bigint;
      end if;
    end loop;
  end if;

  update public.transport_jobs set status = next_status, stock_deducted = stock_deducted or next_status = 'angenommen' where id = transport_job_id returning * into job;
  if job.order_id is not null then
    update public.orders set transport_status = case next_status when 'angenommen' then 'bestaetigt' when 'beladen' then 'bestaetigt' when 'unterwegs' then 'unterwegs' when 'erledigt' then 'zugestellt' when 'storniert' then 'storniert' else 'offen' end where id = job.order_id;
  end if;
  return job;
end;
$$;

revoke execute on function public.pay_invoice(bigint) from anon;
revoke execute on function public.create_order(bigint, jsonb, numeric) from anon;
revoke execute on function public.create_order_with_delivery(bigint, jsonb, numeric, text, text) from anon;
revoke execute on function public.update_transport_status(bigint, text) from anon;
grant execute on function public.pay_invoice(bigint) to authenticated;
grant execute on function public.create_order(bigint, jsonb, numeric) to authenticated;
grant execute on function public.create_order_with_delivery(bigint, jsonb, numeric, text, text) to authenticated;
grant execute on function public.update_transport_status(bigint, text) to authenticated;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique check (username = lower(username) and length(username) between 3 and 40),
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  username text,
  action text not null,
  table_name text not null,
  record_id text,
  old_data jsonb,
  new_data jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin');
$$;

create or replace function public.create_app_user(p_username text, p_password text)
returns public.profiles
language plpgsql
security definer
set search_path = public, auth, extensions
as $$
declare
  clean_username text := lower(trim(p_username));
  new_id uuid := gen_random_uuid();
  new_profile public.profiles;
begin
  if not public.is_admin() then raise exception 'Nur Admins duerfen Benutzer anlegen'; end if;
  if clean_username !~ '^[a-z0-9._-]{3,40}$' then raise exception 'Ungueltiger Benutzername'; end if;
  if p_password is null or length(p_password) < 8 then raise exception 'Das Passwort muss mindestens 8 Zeichen lang sein'; end if;
  insert into auth.users(id, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, aud, role)
    values (new_id, clean_username || '@login.nexora-farming.com', crypt(p_password, gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}'::jsonb, jsonb_build_object('username', clean_username), 'authenticated', 'authenticated');
  insert into public.profiles(id, username) values (new_id, clean_username) returning * into new_profile;
  insert into public.audit_log(user_id, username, action, table_name, record_id, new_data)
    values (auth.uid(), (select username from public.profiles where id = auth.uid()), 'CREATE_USER', 'profiles', new_id::text, jsonb_build_object('username', clean_username));
  return new_profile;
exception when unique_violation then
  raise exception 'Dieser Benutzername ist bereits vergeben';
end;
$$;

grant execute on function public.is_admin() to authenticated;
grant execute on function public.create_app_user(text, text) to authenticated;

create or replace function public.write_audit_log()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  row_data jsonb := case when TG_OP = 'DELETE' then to_jsonb(old) else to_jsonb(new) end;
begin
  insert into public.audit_log(user_id, username, action, table_name, record_id, old_data, new_data)
    values (auth.uid(), (select username from public.profiles where id = auth.uid()), TG_OP, TG_TABLE_NAME,
      coalesce(row_data->>'id', row_data->>'citizen_id', row_data->>'vehicle_id'),
      case when TG_OP in ('UPDATE', 'DELETE') then to_jsonb(old) end,
      case when TG_OP in ('INSERT', 'UPDATE') then to_jsonb(new) end);
  if TG_OP = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

do $$
declare
  table_name text;
begin
  foreach table_name in array array['citizens','companies','accounts','invoices','vehicles','licenses','logistics','logistics_items','company_warehouse','orders','transport_jobs'] loop
    execute format('drop trigger if exists %I on public.%I', 'audit_' || table_name, table_name);
    execute format('create trigger %I after insert or update or delete on public.%I for each row execute function public.write_audit_log()', 'audit_' || table_name, table_name);
  end loop;
end;
$$;

-- Alle fachlichen Seiten sind nur fuer angemeldete Benutzer erreichbar.
alter table public.citizens enable row level security;
alter table public.companies enable row level security;
alter table public.accounts enable row level security;
alter table public.invoices enable row level security;
alter table public.vehicles enable row level security;
alter table public.licenses enable row level security;
alter table public.logistics enable row level security;
alter table public.logistics_items enable row level security;
alter table public.company_warehouse enable row level security;
alter table public.orders enable row level security;
alter table public.transport_jobs enable row level security;

do $$
declare
  table_name text;
begin
  foreach table_name in array array['citizens','companies','accounts','invoices','vehicles','licenses','logistics','logistics_items','company_warehouse','orders','transport_jobs'] loop
    execute format('drop policy if exists %I on public.%I', 'dev_public_access_' || table_name, table_name);
    execute format('drop policy if exists %I on public.%I', 'authenticated_access_' || table_name, table_name);
    execute format('drop policy if exists %I on public.%I', 'authenticated_read_' || table_name, table_name);
    execute format('drop policy if exists %I on public.%I', 'authenticated_insert_' || table_name, table_name);
    execute format('drop policy if exists %I on public.%I', 'admin_update_' || table_name, table_name);
    execute format('drop policy if exists %I on public.%I', 'admin_delete_' || table_name, table_name);
    execute format('create policy %I on public.%I for select to authenticated using (true)', 'authenticated_read_' || table_name, table_name);
    execute format('create policy %I on public.%I for insert to authenticated with check (true)', 'authenticated_insert_' || table_name, table_name);
    execute format('create policy %I on public.%I for update to authenticated using (public.is_admin()) with check (public.is_admin())', 'admin_update_' || table_name, table_name);
    execute format('create policy %I on public.%I for delete to authenticated using (public.is_admin())', 'admin_delete_' || table_name, table_name);
  end loop;
end;
$$;

alter table public.profiles enable row level security;
alter table public.audit_log enable row level security;
drop policy if exists profile_self_or_admin on public.profiles;
create policy profile_self_or_admin on public.profiles for select to authenticated using (id = auth.uid() or public.is_admin());
drop policy if exists audit_admin_read on public.audit_log;
create policy audit_admin_read on public.audit_log for select to authenticated using (public.is_admin());

-- Startkonten: Passwoerter werden als bcrypt-Hash in auth.users gespeichert.
do $$
declare
  admin_id uuid := gen_random_uuid();
  user_id uuid := gen_random_uuid();
begin
  select id into admin_id from auth.users where email in ('nexora.24@login.nexora-farming.com', 'nexora.24@login.gnadental.local') limit 1;
  if admin_id is null then
    admin_id := gen_random_uuid();
    insert into auth.users(id, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, aud, role)
      values (admin_id, 'nexora.24@login.nexora-farming.com', crypt('Geswalriga.06', gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}'::jsonb, '{"username":"nexora.24"}'::jsonb, 'authenticated', 'authenticated');
  else
    update auth.users set email = 'nexora.24@login.nexora-farming.com', encrypted_password = crypt('Geswalriga.06', gen_salt('bf')), email_confirmed_at = coalesce(email_confirmed_at, now()), deleted_at = null where id = admin_id;
  end if;
  insert into public.profiles(id, username, role) values (admin_id, 'nexora.24', 'admin')
    on conflict (username) do update set id = excluded.id, role = 'admin';

  select id into user_id from auth.users where email in ('santobarbosa@login.nexora-farming.com', 'santobarbosa@login.gnadental.local') limit 1;
  if user_id is null then
    user_id := gen_random_uuid();
    insert into auth.users(id, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, aud, role)
      values (user_id, 'santobarbosa@login.nexora-farming.com', crypt('MozaGeswalriga.06', gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}'::jsonb, '{"username":"santobarbosa"}'::jsonb, 'authenticated', 'authenticated');
  else
    update auth.users set email = 'santobarbosa@login.nexora-farming.com', encrypted_password = crypt('MozaGeswalriga.06', gen_salt('bf')), email_confirmed_at = coalesce(email_confirmed_at, now()), deleted_at = null where id = user_id;
  end if;
  insert into public.profiles(id, username, role) values (user_id, 'santobarbosa', 'admin')
    on conflict (username) do update set id = excluded.id, role = 'admin';
end;
$$;

do $$
begin
  alter publication supabase_realtime add table public.citizens;
  alter publication supabase_realtime add table public.companies;
  alter publication supabase_realtime add table public.accounts;
  alter publication supabase_realtime add table public.invoices;
  alter publication supabase_realtime add table public.vehicles;
  alter publication supabase_realtime add table public.licenses;
  alter publication supabase_realtime add table public.logistics_items;
  alter publication supabase_realtime add table public.company_warehouse;
  alter publication supabase_realtime add table public.orders;
  alter publication supabase_realtime add table public.transport_jobs;
exception when duplicate_object then null;
end;
$$;

-- Optionale Startdaten. IDs werden nur einmal angelegt.
insert into public.citizens(citizen_id, first_name, last_name, birthdate)
values ('CIT-0001', 'Max', 'Muster', '1990-05-12')
on conflict (citizen_id) do nothing;

insert into public.companies(company_name, owner_citizen_id, sector, description, status)
select 'Gnadental Agrar', 'CIT-0001', 'Landwirtschaft', 'Beispielbetrieb fuer den Start', 'active'
where not exists (select 1 from public.companies where company_name = 'Gnadental Agrar');

insert into public.companies(company_name, sector, description, status)
select 'Mezzorik Logistik', 'Logistik', 'Zentraler Logistikbetrieb und Kataloganbieter', 'active'
where not exists (select 1 from public.companies where lower(company_name) = 'mezzorik logistik');

insert into public.accounts(type, company_id, balance, status)
select 'unternehmen', companies.id, 0, 'active'
from public.companies
where lower(companies.company_name) = 'mezzorik logistik'
  and not exists (select 1 from public.accounts where company_id = companies.id);

insert into public.accounts(type, citizen_id, balance, status)
select 'privat', 'CIT-0001', 10000, 'active'
where not exists (select 1 from public.accounts where citizen_id = 'CIT-0001');

insert into public.logistics_items(item_name, unit_price, quantity)
values ('Weizen', 250, 100), ('Mais', 220, 100), ('Duenger', 180, 50)
on conflict (item_name) do nothing;